steps:
- name: 'gcr.io/cloud-builders/ng'
  args: ['build', './client' ,'--prod']
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/health-app-client', './client' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/health-app-server', './backend' ]
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['container', 'clusters', 'create', '--num-nodes=2' ,'health-app-cluster']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-west2-b'
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['container', 'clusters', 'get-credentials', 'health-app-cluster']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-west2-b'
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['create', '-R', '-f','./deployment.yaml']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-west2-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=health-app-cluster'