#################################################################
# Dockerfile para configurar aplicacion Node. JS Express 
#################################################################


# Imagen BASE
FROM node

# METADATA
LABEL maintainer="mazg95@live.com"
LABEL version="1.0"

# Crear directorio de trabajo
# Establece directorio de trabajo
WORKDIR /usr/src/app

COPY ./package*.json ./

# Instala los paquetes existentes en el package.json
# Dependencias de la app
RUN npm install --quiet --only=production

COPY . .

EXPOSE 3000
CMD ["npm", "start"]
