#################################################################
# Dockerfile para configurar aplicacion Node. JS Express 
#################################################################


# Imagen BASE
FROM node:8

# METADATA
LABEL maintainer="mazg95@live.com"
LABEL version="1.0"

# Crear directorio de trabajo
# Establece directorio de trabajo
WORKDIR /usr/src/app

COPY ./package*.json ./

# Instala los paquetes existentes en el package.json
# Dependencias de la app
RUN npm install --quiet --only=production

COPY . .

EXPOSE 8080


# Instalar Nodemon para reiniciar el servidor al haber cambios.
RUN npm install nodemon -g --quiet


EXPOSE 8000

CMD nodemon -L --watch . ./app.js
